---
- name: Configure IOS XR Physical Interface Parameters
  iosxr_interfaces:
    config: "{{ physical_interfaces }}"

- name: Configure IOS XR Logical Interface Parameters
  iosxr_l3_interfaces:
    config: "{{ logical_interfaces }}"
